services:
  jupyter:
    build:
      context: .
    ports:
      - 8892:8888
    volumes:
      - type: bind
        source: ./
        target: /home/jovyan/work
    command: start-notebook.py --NotebookApp.token='m'